CoolBooks/CoolBooks/Models/Book.cs
namespace CoolBooks
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Linq;
	using System.Web.Mvc;

	public partial class Book
	{
		public Book()
		{
			this.Reviews = new HashSet<Review>();
		}
		[Required]
		public int Id { get; set; }
		[Required]
		public string UserId { get; set; }
		[Required]
		public int AuthorId { get; set; }
		[Required]
		public int GenreId { get; set; }
		[Required]
		public string Title { get; set; }
		public string AlternativeTitle { get; set; }
		public Nullable<short> Part { get; set; }
		[Required]
		public string Description { get; set; }
		[Remote("IsISBNExists", "Books", AdditionalFields = "Id", ErrorMessage = "ISBN already exists")]
		public string ISBN { get; set; }
		public Nullable<System.DateTime> PublishDate { get; set; }
		[Required]
		public string ImagePath { get; set; }
		[Required]
		public System.DateTime Created { get; set; }
		public bool IsDeleted { get; set; }

	
		public float Rating
		{
			get
			{
				if (Reviews.Count > 0)
				{
					return Reviews.Where(x => !x.IsDeleted).Sum(x => (int)x.Rating) / Reviews.Count(x => !x.IsDeleted);
				}
				else { return 0; }
			}
		}
		
		public int Ratings
		{
			get { return Reviews.Count(x => !x.IsDeleted); }
		}

		public virtual Author Author { get; set; }
		public virtual Genre Genre { get; set; }

		public virtual ICollection<Review> Reviews { get; set; }
		public virtual AspNetUser AspNetUser { get; set; }
	}
}

CoolBooks/CoolBooks/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CoolBooks;
using Microsoft.AspNet.Identity;
using CoolBooks.Classes;

namespace CoolBooks.Controllers
{
    public class BooksController : Controller
    {
        private CoolBooksEntities db = new CoolBooksEntities();

		public JsonResult IsISBNExists(string isbn, int Id = 0)
		{
			Book book = db.Books.FirstOrDefault(b => b.ISBN == isbn);
			if (book == null || book.Id == Id)
			{
				return Json(true, JsonRequestBehavior.AllowGet);
			}
			else
			{
				return Json(false, JsonRequestBehavior.AllowGet);
			}
		}

		[ChildActionOnly]
		public ActionResult ShowReviews(int Id)
		{
			var model = new List<Review>();
			if(User.IsInRole("Admin"))
			{
				model = db.Reviews.Where(r => r.BookId == Id).OrderByDescending(x => x.Created).ToList();
			}
			else
			{
				var userId = User.Identity.GetUserId();
				model = db.Reviews.Where(r => r.BookId == Id && (!r.IsDeleted || r.UserId == userId)).OrderByDescending(x => x.Created).ToList();
			}
			if (model.Count() == 0)
			{
				return Content("No reviews yet");
			}
			else
			{
				return PartialView(model);
			}
		}

		// GET: Books
	    public ActionResult Index()
        {
			var books = new List<Book>();
			//Admin gets all the books
			if(User.IsInRole("Admin"))
			{
				books = db.Books.Include(b => b.Author).Include(b => b.Genre).Include(b => b.AspNetUser).ToList();
			}
			//Users gets all books in the system, and ones added by themselves.
			else if(User.Identity.IsAuthenticated)
			{
				var userId = User.Identity.GetUserId();
				books = db.Books.Where(b => !b.IsDeleted || b.UserId == userId).Include(b => b.Author).Include(b => b.Genre).Include(b => b.AspNetUser).ToList();
			}
			//Unreged users gets all non-deleted books.
			else
			{
				books = db.Books.Where(b => !b.IsDeleted).Include(b => b.Author).Include(b => b.Genre).Include(b => b.AspNetUser).ToList();

			}

			//Shuld have one to show all for admins
			return View(books);
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }
		[Authorize]
        // GET: Books/Create
        public ActionResult Create()
        {
			var autorNameList = ControllerMethods.AuthorsFullName();


			ViewBag.AuthorId = new SelectList(autorNameList, "Value", "Text");
			ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name");
			ViewBag.UserId = User.Identity.GetUserId();
			ViewBag.Created = DateTime.Now;

			var book = new Book()
			{
				Created = DateTime.Now,
				UserId = User.Identity.GetUserId()
			};
			return View(book);
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
		[Authorize]
		[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,AuthorId,GenreId,Title,AlternativeTitle,Part,Description,ISBN,PublishDate,ImagePath,Created,IsDeleted")] Book book)
        {
			if(db.Books.Any(b => b.ISBN == book.ISBN && b.Id != book.Id))
			{
				book.ISBN = "Already in database";
				return View("Create", book);
			}
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
			//Creates a list with both first and lastname
			var autorNameList = ControllerMethods.AuthorsFullName();
			ViewBag.AuthorId = new SelectList(autorNameList, "Value", "Text");
            ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name", book.GenreId);
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", book.UserId);
            return View(book);
        }

        // GET: Books/Edit/5
		[AuthorizeCreatorAndAdmin]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }

			//Creates a list with both first and lastname
			var autorNameList = ControllerMethods.AuthorsFullName();
			ViewBag.AuthorId = new SelectList(autorNameList, "Value", "Text");
			ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name", book.GenreId);
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", book.UserId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
		[AuthorizeCreatorAndAdmin]
		[ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,AuthorId,GenreId,Title,AlternativeTitle,Part,Description,ISBN,PublishDate,ImagePath,Created,IsDeleted")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorId = new SelectList(db.Authors, "Id", "FirstName", book.AuthorId);
            ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name", book.GenreId);
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", book.UserId);
            return View(book);
        }

		protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



    }
}

CoolBooks/CoolBooks/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CoolBooks;
using Microsoft.AspNet.Identity;
using CoolBooks.Classes;

namespace CoolBooks.Controllers
{
    public class ReviewsController : Controller
    {
        private CoolBooksEntities db = new CoolBooksEntities();

		// GET: Reviews
		[Authorize(Roles = "Admin")]
		public ActionResult Index()
        {
            var reviews = db.Reviews.Include(r => r.Book).Include(r => r.AspNetUser);
            return View(reviews.ToList());
        }

        // GET: Reviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

		// GET: Reviews/Create
		[Authorize]
		public ActionResult Create(int bookid)
        {
			var book = (from r in db.Books
						where r.Id ==bookid
						select r).First();
			var _review = (new Review { BookId = book.Id,
							UserId = User.Identity.GetUserId(),
							Created=DateTime.Now
			});
			ViewBag.BookTitle = book.Title;
			ViewBag.BookPath = book.ImagePath;

			return View(_review);
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
		[Authorize]
		[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookId,UserId,Title,Text,Rating,Created,IsDeleted")] Review review) //id
        {
			review.Created = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Reviews.Add(review);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BookId = new SelectList(db.Books, "Id", "UserId", review.BookId);
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", review.UserId);
            return View(review);
        }

        // GET: Reviews/Edit/5
		[AuthorizeCreatorAndAdmin]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            ViewBag.BookId = new SelectList(db.Books, "Id", "Title", review.BookId);
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", review.UserId);
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
		[AuthorizeCreatorAndAdmin]
		[ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BookId,UserId,Title,Text,Rating,Created,IsDeleted")] Review review)
        {
            if (ModelState.IsValid)
            {
				if(!User.IsInRole("Admin"))
				{
					review.UserId = User.Identity.GetUserId();
				}
                db.Entry(review).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BookId = new SelectList(db.Books, "Id", "UserId", review.BookId);
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", review.UserId);
            return View(review);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CoolBooks/CoolBooks/Views/Books/Create.cshtml
@model CoolBooks.Book

@{
    ViewBag.Title = "Create";
}

<h1>Add books</h1>
<hr />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.AuthorId, "AuthorId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreId, "GenreId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlternativeTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlternativeTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlternativeTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Part, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Part, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Part, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublishDate, htmlAttributes: new {@class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control",@type="date" } })
                @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control", @type="url" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

		@*UserID and Created hidden from the user*@
 		@Html.Hidden("UserId")
		@Html.Hidden("Created")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CoolBooks/CoolBooks/Views/Books/Details.cshtml
@model CoolBooks.Book

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <h2>@Model.Title</h2>
    <hr />
    <dl class="dl-horizontal col-md-10">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            Alternative title
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlternativeTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Part)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Part)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ISBN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublishDate)
        </dt>

        <dd>
            @{
				//Bör snyggas upp så att ifsatsen inte behövs.
				if (Model.PublishDate != null)
				{
					@Html.DisplayFor(modelItem => Model.PublishDate.Value.Year)
				}
			}
        </dd>
        <dt>
            Author
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.FirstName) @Html.DisplayFor(model => model.Author.LastName)
        </dd>

        <dt>
           Genre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>
    </dl>
	<div class="col-md-2">
		<img src="@Html.DisplayFor(model => model.ImagePath)" class="img-responsive img-rounded" alt="Book cover" />
	</div>
</div>

<p class="container row">
	@if(User.IsInRole("Admin") || Model.UserId == User.Identity.GetUserId())
	{ 
		@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) 
		@: | 
		@Html.ActionLink("Back to List", "Index")
		@: | 
	}
	
	@if (User.Identity.IsAuthenticated)
	{
		@Html.ActionLink("Add review", "Create", "Reviews", new { bookid = Model.Id }, null)
	}
</p>
<hr /> 
@Html.Action("ShowReviews", Model.Id)

CoolBooks/CoolBooks/Views/Books/Edit.cshtml
@model CoolBooks.Book

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

		@if(User.IsInRole("Admin"))
		{
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>
		}
        <div class="form-group">
            @Html.LabelFor(model => model.AuthorId, "Author", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreId, "Genre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlternativeTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlternativeTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlternativeTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Part, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Part, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Part, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublishDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeleted)
                    @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CoolBooks/CoolBooks/Views/Books/Index.cshtml
@model IEnumerable<CoolBooks.Book>

@{
	ViewBag.Title = "Index";
}

	<h2>Result	</h2>
<p>
	@if (User.Identity.IsAuthenticated) { @Html.ActionLink("Create New", "Create") }
</p>

<table class="table sort" id="sort">
	<thead>
		<tr>
			<th role="columnheader">
				@Html.DisplayName("Cover")
			</th>
			<th data-sort-default role="columnheader">
				@Html.DisplayNameFor(model => model.Title)
			</th>
			<th role="columnheader">
				@Html.DisplayNameFor(model => model.Description)
			</th>
			<th role="columnheader">
				@Html.DisplayName("Published")
			</th>

			<th colspan="2" role="columnheader">
				@Html.DisplayName("Author")
			</th>
			<th role="columnheader">
				@Html.DisplayName("Genre")
			</th>
			@if (User.IsInRole("Admin"))
			{
				<th role="columnheader">
					@Html.DisplayName("Deleted")
				</th>
			}
			<th role="columnheader"></th>
		</tr>
	</thead>
	@foreach (var item in Model)
	{
		<tr>
			<td>
				<a href="@Url.Action("Details", "Books", new { id = item.Id})">
				<img src="@Html.DisplayFor(modelItem => item.ImagePath)" class="img-responsive img-rounded" alt="Book cover" />
				</a>

</td>
			<td>
				@Html.DisplayFor(modelItem => item.Title)
			</td>
			<td>
				@ParseOutput.Truncate(item.Description, 300)

			</td>
			<td>

				@{
					//Bör snyggas upp så att ifsatsen inte behövs.
					if (item.PublishDate != null)
					{
						@Html.DisplayFor(modelItem => item.PublishDate.Value.Year)
				}
				}
			</td>

			<td colspan="2">
				@Html.DisplayFor(modelItem => item.Author.FirstName) @Html.DisplayFor(modelItem => item.Author.LastName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Genre.Name)
			</td>
		
			@if (User.IsInRole("Admin"))
			{
				<td>
					@Html.DisplayFor(modelItem => item.IsDeleted)
				</td>
			}
			<td>
				<ul>
					<li>
						@Html.ActionLink("Details", "Details", "Books", new { id = item.Id }, null)
					</li>
					@if (User.IsInRole("Admin") || User.Identity.GetUserId() == item.UserId)
					{
					<li>
						@Html.ActionLink("Edit", "Edit", "Books", new { id = item.Id }, null)
					</li>
					}
					<li>
						@Html.ActionLink("Add review", "Create", "Reviews", new { bookid = item.Id }, null)
					</li>
				</ul>
			</td>
		</tr>
					}

</table>

<script>
	new Tablesort(document.getElementById('sort'));
</script>

CoolBooks/CoolBooks/Views/Books/ShowReviews.cshtml
@model ICollection<CoolBooks.Review>
<h2>Reviews:</h2>
@foreach (var item in Model)
{
<details>
	<summary>
		<b>@item.Title (@item.Rating)</b>
		@if (item.IsDeleted)
		{
			<i>(Has been deleted)</i>
		}
	</summary>

	<p>@item.Text</p>
	@{
		string linkText = $"{item.AspNetUser.UserName} ({item.Created.ToShortDateString()})";
	}
	<p><i> @Html.ActionLink(linkText, "Details", "Reviews", new { Id = item.Id }, null)</i></p>
</details>
}