CoolBooks/CoolBooks/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CoolBooks;
using Microsoft.AspNet.Identity;
using CoolBooks.Classes;

namespace CoolBooks.Controllers
{
    public class BooksController : Controller
    {
        private CoolBooksEntities db = new CoolBooksEntities();

		public JsonResult IsISBNExists(string isbn, int Id = 0)
		{
			Book book = db.Books.FirstOrDefault(b => b.ISBN == isbn);
			if (book == null || book.Id == Id)
			{
				return Json(true, JsonRequestBehavior.AllowGet);
			}
			else
			{
				return Json(false, JsonRequestBehavior.AllowGet);
			}
		}

		[ChildActionOnly]
		public ActionResult ShowReviews(int Id)
		{
			var model = new List<Review>();
			if(User.IsInRole("Admin"))
			{
				model = db.Reviews.Where(r => r.BookId == Id).OrderByDescending(x => x.Created).ToList();
			}
			else
			{
				var userId = User.Identity.GetUserId();
				model = db.Reviews.Where(r => r.BookId == Id && (!r.IsDeleted || r.UserId == userId)).OrderByDescending(x => x.Created).ToList();
			}
			if (model.Count() == 0)
			{
				return Content("No reviews yet");
			}
			else
			{
				return PartialView(model);
			}
		}

		// GET: Books
	    public ActionResult Index()
        {
			var books = new List<Book>();
			//Admin gets all the books
			if(User.IsInRole("Admin"))
			{
				books = db.Books.Include(b => b.Author).Include(b => b.Genre).Include(b => b.AspNetUser).ToList();
			}
			//Users gets all books in the system, and ones added by themselves.
			else if(User.Identity.IsAuthenticated)
			{
				var userId = User.Identity.GetUserId();
				books = db.Books.Where(b => !b.IsDeleted || b.UserId == userId).Include(b => b.Author).Include(b => b.Genre).Include(b => b.AspNetUser).ToList();
			}
			//Unreged users gets all non-deleted books.
			else
			{
				books = db.Books.Where(b => !b.IsDeleted).Include(b => b.Author).Include(b => b.Genre).Include(b => b.AspNetUser).ToList();

			}

			//Shuld have one to show all for admins
			return View(books);
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }
		[Authorize]
        // GET: Books/Create
        public ActionResult Create()
        {
			var autorNameList = ControllerMethods.AuthorsFullName();


			ViewBag.AuthorId = new SelectList(autorNameList, "Value", "Text");
			ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name");
			ViewBag.UserId = User.Identity.GetUserId();
			ViewBag.Created = DateTime.Now;

			var book = new Book()
			{
				Created = DateTime.Now,
				UserId = User.Identity.GetUserId()
			};
			return View(book);
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
		[Authorize]
		[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,AuthorId,GenreId,Title,AlternativeTitle,Part,Description,ISBN,PublishDate,ImagePath,Created,IsDeleted")] Book book)
        {
			if(db.Books.Any(b => b.ISBN == book.ISBN && b.Id != book.Id))
			{
				book.ISBN = "Already in database";
				return View("Create", book);
			}
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
			//Creates a list with both first and lastname
			var autorNameList = ControllerMethods.AuthorsFullName();
			ViewBag.AuthorId = new SelectList(autorNameList, "Value", "Text");
            ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name", book.GenreId);
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", book.UserId);
            return View(book);
        }

        // GET: Books/Edit/5
		[AuthorizeCreatorAndAdmin]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }

			//Creates a list with both first and lastname
			var autorNameList = ControllerMethods.AuthorsFullName();
			ViewBag.AuthorId = new SelectList(autorNameList, "Value", "Text");
			ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name", book.GenreId);
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", book.UserId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
		[AuthorizeCreatorAndAdmin]
		[ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,AuthorId,GenreId,Title,AlternativeTitle,Part,Description,ISBN,PublishDate,ImagePath,Created,IsDeleted")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorId = new SelectList(db.Authors, "Id", "FirstName", book.AuthorId);
            ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name", book.GenreId);
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", book.UserId);
            return View(book);
        }

		protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



    }
}

CoolBooks/CoolBooks/Controllers/HighRankedController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CoolBooks;
using CoolBooks.Models;

namespace CoolBooks.Controllers
{
	public class HighRankedController : Controller
	{
		private CoolBooksEntities db = new CoolBooksEntities();
		protected class dictval
		{
			public dictval(int i,int start)
			{
				id = i;
				total = start;
				nr = 1;
			}
			public void add(int ad)
			{
				total += ad;
				nr++;
			}
			int id;
			int total = 0;
			int nr = 0;
			public int ID { get { return id; } set {id=value; } }
			public int Total { get { return total; } set { total = value; } }
			public int NR { get { return nr; } set { nr = value; } }
		}


		public ActionResult MostRatedView()
		{
			var model = db.Books.ToList().OrderByDescending(x => x.Ratings).Take(5);
			

			return PartialView(model);
		}

		// GET: HighRanked
		public ActionResult HighRankedView()
		{

			var model = db.Books.ToList().OrderByDescending(x => x.Rating).Take(5);

			return PartialView(model);
		}
		public ActionResult LatestRanked()
		{

			var model = db.Reviews.Where(x => !x.IsDeleted).OrderByDescending(x => x.Created).Take(5).ToList();

			return PartialView(model);
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

CoolBooks/CoolBooks/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CoolBooks;

namespace CoolBooks.Controllers
{
    public class SearchController : Controller
    {
        private CoolBooksEntities db = new CoolBooksEntities();

        // GET: Search
        public ActionResult Index(string search)
        {
            var title = db.Books.Where(x => x.Title.Contains(search) && !(x.IsDeleted)).Include(b => b.Author).ToList();
            var author = db.Books.Where(x => x.Author.LastName.Contains(search) && !(x.IsDeleted)).Include(b => b.Author).ToList();

            var books = title.Union(author);
            return View(books);
        }


        // GET: AdvancedSearch
        public ActionResult AdvancedSearch(string search)
        {
            var titleSearch = HttpContext.Request.Params.Get("Booktitle");
            var authorSearch = HttpContext.Request.Params.Get("Author");
            var genreSearch = HttpContext.Request.Params.Get("Genre");
            var isbnSearch = HttpContext.Request.Params.Get("ISBN");

            ViewBag.Booktitle = titleSearch;
            ViewBag.Author = authorSearch;
            ViewBag.Genre = genreSearch;
            ViewBag.ISBN = isbnSearch;

            var searchResult = db.Books.Where
                (x => x.Title.Contains(titleSearch) && 
                x.Author.LastName.Contains(authorSearch) && 
                x.Genre.Name.Contains(genreSearch) && 
                x.ISBN.Contains(isbnSearch) && !(x.IsDeleted)).Include(b => b.Author).ToList();

            return View("Index",searchResult);
        }
		
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CoolBooks/CoolBooks/Views/Shared/HighRankedView.cshtml
@model IEnumerable<Book>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
@*<h1>here we should have highertst rated books</h1>*@
<h2>Top 5 Ratings</h2>
<ul>
	@foreach (var item in Model)
	{
		<li >
			
				<a href="@Url.Action("Details", "Books", new { id = item.Id})">
					<img class="img-responsive img-rounded" src=@item.ImagePath
						 alt="Missing picture url: @item.ImagePath"
						 style="max-width:100px;max-height:150px;">
				</a>
				@*<p>
					@item.Title	
				</p>*@
			
		</li>
	}
</ul>

CoolBooks/CoolBooks/Views/Shared/LatestRanked.cshtml
@model IEnumerable<Review>

<h2 style="text-align:center">Latest Reviews</h2>
<ul>
	@foreach (var item in Model)
	{
		<li>

			<a href="@Url.Action("Details", "Books", new { id = item.Book.Id})">
				<img class="img-responsive img-rounded" src=@item.Book.ImagePath
					 alt="Missing picture url: @item.Book.ImagePath"
					 style="max-width:100px;max-height:150px;">
			</a>
			@*<p>
					@item.Title
				</p>*@

		</li>
	}
</ul>

CoolBooks/CoolBooks/Views/Shared/MostRatedView.cshtml
@model IEnumerable<Book>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<h2>Most Rated</h2>
<ul>
	@foreach (var item in Model)
	{
		<li>

			<a href="@Url.Action("Details", "Books", new { id = item.Id})">
				<img class="img-responsive img-rounded" src=@item.ImagePath
					 alt="Missing picture url: @item.ImagePath"
					  style="max-width:100px;max-height:150px;">
			</a>
			@*<p>
				@item.Title
			</p>*@

		</li>
	}
</ul>

CoolBooks/CoolBooks/Views/Shared/_BookList.cshtml
@model IEnumerable<Book>
<aside>
	@foreach (var item in Model)
	{
		<img src="@item.ImagePath" class="img-responsive img-responsive" /><br />
		@item.Title<br />
	}
</aside>

CoolBooks/CoolBooks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/Scripts/CustomJS.js")
	@Scripts.Render("~/Scripts/tablesort.js")


</head>
<body>
	<div class="container-fluid">
		<aside class="col-md-2">
			@{Html.RenderAction("LatestRanked", "HighRanked");}
		</aside>
		<div class="col-md-8">
			<div class="navbar navbar-inverse navbar-fixed-top">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					@Html.ActionLink("Cool Books", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">

						@if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
						{
							<li>@Html.ActionLink("Add Book", "Create", "Books")</li>
						}
						@if (User.IsInRole("Admin"))
						{
							<li>@Html.ActionLink("Books", "Index", "Books")</li>
							<li>@Html.ActionLink("Reviews", "Index", "Reviews")</li>
							<li>@Html.ActionLink("Authors", "Index", "Authors")</li>
							<li>@Html.ActionLink("Genres", "Index", "Genres")</li>
						}
						<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
						<li> @Html.Partial("_LoginPartial")</li>
                        <li class="searchbar">@Html.Partial("_SearchBarPartial")</li>
					</ul>

				</div>
			</div>
			<div class="container" style="align-items:center">
				@RenderBody()
			
				<footer>
					<hr />
					<p>Last update: @File.GetLastWriteTime(this.Server.MapPath(this.VirtualPath)).ToString(@"yyyy-MM-dd HH:mm")</p>
				</footer>
			</div>

		</div>
		<aside class="col-md-2">
			@{Html.RenderAction("HighRankedView", "HighRanked");}
		</aside>
	</div>

	


	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")

	@RenderSection("scripts", required: false)
</body>
</html>

CoolBooks/CoolBooks/Views/Shared/_SearchBarPartial.cshtml
@using (Html.BeginForm("Index", "Search",FormMethod.Get))
{
	@Html.TextBox("Search")
	<input type="submit" value="Search" />
}

	@*<div class="container">
	<form class="navbar-form navbar-left" role="Search">
		<div class="form-group">
			<input type="text" class="form-control col-xs-8" placeholder="Search" name="Search">
		</div>
			<button type="submit" class="btn btn-default col-xs-4">
				<span class="glyphicon glyphicon-search"></span>
			</button>	
	</form>
	</div>*@